[package]
name = "rust_mud_driver"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
chrono = "0.4"
dns-lookup = "1.0"

[[bin]]
name = "rust_mud_driver"
path = "src/main.rs"

[lib]
name = "rust_mud_driver"
path = "src/lib.rs"
